### ISSUE TITLE
[Bug] [scaleph-storage] scaleph minio fails when hadoop bootstraped on same machine

### ISSUE THREAD

**Issue by kalencaya** [flowerfine/scaleph#119]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

dev

### What happened

When hadoop bootstraps, scaleph would connect minio failed for network failure, even minio works normally.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kalencaya** [comment]
When hadoop runs on same machine with `scaleph-api`, `scaleph-api` has to use HDFS as its storage.
```
file-system:
#  type: local
#  type: s3
#  proxy: false
#  bucket: ${spring.application.name}
#  endPoint: http://127.0.0.1:9000
#  accessKey: admin
#  secretKey: password
#  type: oss
#  bucket: ${spring.application.name}
#  endPoint: Aliyun OSS endpoint to connect to
#  accessKey: Aliyun access key ID
#  secretKey: Aliyun access key secret
  type: hdfs
  hadoopConfPath: Hadoop conf path
  defaultFS: hdfs://namenode:9000
```
But it is also confused for me why `scaleph-api` with minio can't work well, when hadoop exists.
